"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { prisma } from "@/lib/prisma";
import { requireAccess } from "@/services/users/access.service";
import { getCurrentUser } from "@/services/users/current-user.service";

const allowedRoles = ["ADMIN", "GOVERNANCE_TEAM", "ENGAGEMENT_MANAGER", "PROJECT_MANAGER"];
const allWorkflowRoles = [
  "ADMIN",
  "GOVERNANCE_TEAM",
  "ENGAGEMENT_MANAGER",
  "PROJECT_MANAGER",
  "VALIDATOR",
  "QA_REVIEWER",
  "REVIEWER",
  "RETESTER",
];
const sensitiveKeys = new Set([
  "phone",
  "phoneNumber",
  "currentCtc",
  "expectedCtc",
  "noticePeriod",
  "salary",
  "salaryNegotiation",
]);

function text(formData: FormData, key: string) {
  if (sensitiveKeys.has(key)) return "";
  return String(formData.get(key) ?? "").trim();
}

function optionalDate(value: string) {
  if (!value) return null;
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

function numberValue(formData: FormData, key: string) {
  const value = Number(text(formData, key));
  if (!Number.isFinite(value)) return 0;
  return Math.max(0, Math.min(5, value));
}

function nextCandidateCode(kind: string) {
  const prefix = kind === "Internal" ? "INT" : "EXT";
  return `${prefix}-${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`;
}

async function actorName() {
  const currentUser = await getCurrentUser();
  return currentUser?.name ?? currentUser?.email ?? "System";
}

async function audit(profileId: string, action: string, fieldChanged?: string, previousValue?: string | null, newValue?: string | null) {
  await prisma.interviewAudit.create({
    data: {
      profileId,
      user: await actorName(),
      action,
      fieldChanged,
      previousValue: previousValue ?? undefined,
      newValue: newValue ?? undefined,
    },
  });
}

function redirectTarget(formData: FormData) {
  const returnTo = text(formData, "returnTo");

  if (returnTo.startsWith("/workflow/interview-agent")) {
    return returnTo;
  }

  return "/workflow/interview-agent";
}

function interviewRedirect(kind: "success" | "error", message: string, returnTo = "/workflow/interview-agent"): never {
  const separator = returnTo.includes("?") ? "&" : "?";
  redirect(`${returnTo}${separator}${kind}=${encodeURIComponent(message)}`);
}

export async function createInterviewProfile(formData: FormData) {
  await requireAccess(allowedRoles);

  const interviewKind = text(formData, "interviewKind") === "Internal" ? "Internal" : "External";
  const name = text(formData, "name");

  if (!name) {
    interviewRedirect("error", "Name is required.");
  }

  const profile = await prisma.interviewProfile.create({
    data: {
      candidateCode: nextCandidateCode(interviewKind),
      interviewKind,
      name,
      employeeId: interviewKind === "Internal" ? text(formData, "employeeId") || null : null,
      currentTeam: interviewKind === "Internal" ? text(formData, "currentTeam") || null : null,
      currentRole: text(formData, "currentRole") || null,
      experience: text(formData, "experience") || null,
      skills: text(formData, "skills") || null,
      certifications: text(formData, "certifications") || null,
      currentProject: interviewKind === "Internal" ? text(formData, "currentProject") || null : null,
      resumeFileName: interviewKind === "External" ? text(formData, "resumeFileName") || null : null,
      linkedIn: interviewKind === "External" ? text(formData, "linkedIn") || null : null,
      source: interviewKind === "External" ? text(formData, "source") || null : null,
      assignedRecruiterId: text(formData, "assignedRecruiterId") || null,
      hiringManagerId: text(formData, "hiringManagerId") || null,
      priority: text(formData, "priority") || "Medium",
      tags: text(formData, "tags") || null,
      status: interviewKind === "External" ? "Applied / Nominated" : "Nominated",
      audits: {
        create: {
          user: await actorName(),
          action: "Profile created",
          fieldChanged: "interviewKind",
          newValue: interviewKind,
        },
      },
      actions: {
        create: {
          actionType: interviewKind === "External" ? "Interview Pending" : "Mock Interview Pending",
          ownerId: text(formData, "assignedRecruiterId") || null,
          status: "Open",
          notes: "Initial interview governance action generated by Interview Agent.",
        },
      },
    },
  });

  revalidatePath("/workflow/interview-agent");
  interviewRedirect("success", `${profile.name} was added to interview governance.`, redirectTarget(formData));
}

export async function updateInterviewProfile(formData: FormData) {
  await requireAccess(allowedRoles);
  const profileId = text(formData, "profileId");
  const current = await prisma.interviewProfile.findUnique({ where: { id: profileId } });

  if (!current) {
    interviewRedirect("error", "Interview profile was not found.");
  }

  const nextStatus = text(formData, "status") || current.status;
  const nextPriority = text(formData, "priority") || current.priority;
  const nextTags = text(formData, "tags") || null;

  await prisma.interviewProfile.update({
    where: { id: profileId },
    data: {
      currentRole: text(formData, "currentRole") || null,
      skills: text(formData, "skills") || null,
      certifications: text(formData, "certifications") || null,
      assignedRecruiterId: text(formData, "assignedRecruiterId") || null,
      hiringManagerId: text(formData, "hiringManagerId") || null,
      priority: nextPriority,
      tags: nextTags,
      status: nextStatus,
    },
  });

  if (current.status !== nextStatus) await audit(profileId, "Profile updated", "status", current.status, nextStatus);
  if (current.priority !== nextPriority) await audit(profileId, "Profile updated", "priority", current.priority, nextPriority);
  if ((current.tags ?? "") !== (nextTags ?? "")) await audit(profileId, "Profile updated", "tags", current.tags, nextTags);

  revalidatePath("/workflow/interview-agent");
  interviewRedirect("success", `${current.name} was updated.`, redirectTarget(formData));
}

export async function scheduleInterviewRound(formData: FormData) {
  await requireAccess(allWorkflowRoles);
  const profileId = text(formData, "profileId");
  const category = text(formData, "category") || "Mock Interview";
  const stage = text(formData, "stage") || `${category} Scheduled`;

  const profile = await prisma.interviewProfile.findUnique({ where: { id: profileId } });
  if (!profile) {
    interviewRedirect("error", "Profile is required before scheduling an interview.");
  }

  await prisma.$transaction([
    prisma.interviewRound.create({
      data: {
        profileId,
        category,
        stage,
        status: text(formData, "roundStatus") || "Scheduled",
        ownerId: text(formData, "ownerId") || null,
        primaryInterviewerId: text(formData, "primaryInterviewerId") || null,
        secondaryInterviewerId: text(formData, "secondaryInterviewerId") || null,
        observerId: text(formData, "observerId") || null,
        scheduledAt: optionalDate(text(formData, "scheduledAt")),
        durationMinutes: Number(text(formData, "durationMinutes") || "60"),
        meetingLink: text(formData, "meetingLink") || null,
        comments: text(formData, "comments") || null,
        attachments: text(formData, "attachments") || null,
      },
    }),
    prisma.interviewProfile.update({
      where: { id: profileId },
      data: { status: stage },
    }),
    prisma.interviewAction.create({
      data: {
        profileId,
        actionType: "Feedback Pending",
        ownerId: text(formData, "primaryInterviewerId") || null,
        dueDate: optionalDate(text(formData, "scheduledAt")),
        status: "Open",
        notes: `Feedback required for ${category}.`,
      },
    }),
  ]);

  await audit(profileId, "Interview scheduled", "stage", profile.status, stage);
  revalidatePath("/workflow/interview-agent");
  interviewRedirect("success", `${category} was scheduled for ${profile.name}.`, redirectTarget(formData));
}

export async function saveInterviewFeedback(formData: FormData) {
  await requireAccess(allWorkflowRoles);
  const roundId = text(formData, "roundId");
  const round = await prisma.interviewRound.findUnique({
    where: { id: roundId },
    include: { profile: true },
  });

  if (!round) {
    interviewRedirect("error", "Interview round was not found.");
  }

  const recommendation = text(formData, "finalRecommendation") || "Borderline";
  const completedAt = optionalDate(text(formData, "completedAt")) ?? new Date();
  const nextStatus = recommendation === "Reject" ? "Rejected" : recommendation === "Strong Hire" || recommendation === "Hire" ? "Selected" : "Future Consideration";

  await prisma.$transaction([
    prisma.interviewFeedback.upsert({
      where: { roundId },
      update: {
        technicalKnowledge: numberValue(formData, "technicalKnowledge"),
        communication: numberValue(formData, "communication"),
        problemSolving: numberValue(formData, "problemSolving"),
        securityFundamentals: numberValue(formData, "securityFundamentals"),
        webApplicationSecurity: numberValue(formData, "webApplicationSecurity"),
        apiSecurity: numberValue(formData, "apiSecurity"),
        burpSuite: numberValue(formData, "burpSuite"),
        owasp: numberValue(formData, "owasp"),
        cloudSecurity: numberValue(formData, "cloudSecurity"),
        aiLlmSecurity: numberValue(formData, "aiLlmSecurity"),
        documentation: numberValue(formData, "documentation"),
        overallConfidence: numberValue(formData, "overallConfidence"),
        strengths: text(formData, "strengths") || null,
        areasForImprovement: text(formData, "areasForImprovement") || null,
        additionalNotes: text(formData, "additionalNotes") || null,
        recommendedLearning: text(formData, "recommendedLearning") || null,
        finalRecommendation: recommendation,
      },
      create: {
        roundId,
        technicalKnowledge: numberValue(formData, "technicalKnowledge"),
        communication: numberValue(formData, "communication"),
        problemSolving: numberValue(formData, "problemSolving"),
        securityFundamentals: numberValue(formData, "securityFundamentals"),
        webApplicationSecurity: numberValue(formData, "webApplicationSecurity"),
        apiSecurity: numberValue(formData, "apiSecurity"),
        burpSuite: numberValue(formData, "burpSuite"),
        owasp: numberValue(formData, "owasp"),
        cloudSecurity: numberValue(formData, "cloudSecurity"),
        aiLlmSecurity: numberValue(formData, "aiLlmSecurity"),
        documentation: numberValue(formData, "documentation"),
        overallConfidence: numberValue(formData, "overallConfidence"),
        strengths: text(formData, "strengths") || null,
        areasForImprovement: text(formData, "areasForImprovement") || null,
        additionalNotes: text(formData, "additionalNotes") || null,
        recommendedLearning: text(formData, "recommendedLearning") || null,
        finalRecommendation: recommendation,
      },
    }),
    prisma.interviewRound.update({
      where: { id: roundId },
      data: {
        status: "Completed",
        completedAt,
      },
    }),
    prisma.interviewProfile.update({
      where: { id: round.profileId },
      data: { status: nextStatus },
    }),
    prisma.interviewAction.updateMany({
      where: {
        profileId: round.profileId,
        actionType: "Feedback Pending",
        status: "Open",
      },
      data: { status: "Closed" },
    }),
  ]);

  await audit(round.profileId, "Feedback saved", "finalRecommendation", round.profile.status, recommendation);
  revalidatePath("/workflow/interview-agent");
  interviewRedirect("success", `Feedback was saved for ${round.profile.name}.`, redirectTarget(formData));
}

export async function saveCapabilityRating(formData: FormData) {
  await requireAccess(allWorkflowRoles);
  const profileId = text(formData, "profileId");
  const technology = text(formData, "technology");
  const rating = text(formData, "rating") || "Beginner";

  if (!profileId || !technology) {
    interviewRedirect("error", "Profile and technology are required.");
  }

  await prisma.interviewCapability.upsert({
    where: {
      profileId_technology: {
        profileId,
        technology,
      },
    },
    update: { rating },
    create: { profileId, technology, rating },
  });

  await audit(profileId, "Capability updated", technology, undefined, rating);
  revalidatePath("/workflow/interview-agent");
  interviewRedirect("success", `${technology} capability was saved.`, redirectTarget(formData));
}

export async function updateInterviewAction(formData: FormData) {
  await requireAccess(allWorkflowRoles);
  const actionId = text(formData, "actionId");
  const status = text(formData, "status") || "Closed";
  const action = await prisma.interviewAction.update({
    where: { id: actionId },
    data: { status },
    include: { profile: true },
  });

  await audit(action.profileId, "Action updated", action.actionType, undefined, status);
  revalidatePath("/workflow/interview-agent");
  interviewRedirect("success", `${action.actionType} was updated for ${action.profile.name}.`, redirectTarget(formData));
}
