export type SecurityControl = {
  id: string;
  title: string;
  category: string;
  owasp: string;
  cwe?: string;
  defaultSeverity: "Critical" | "High" | "Medium" | "Low" | "INFO" | "Not Rated";
  detail: string;
  reviewerGuidance: string;
  remediation: string;
};

export const securityControls: SecurityControl[] = [
  {
    id: "0.1",
    title: "Security review notification and stakeholder awareness",
    category: "Review Authorization",
    owasp: "A04 Insecure Design",
    defaultSeverity: "INFO",
    detail: "Application stakeholders should be aware that the security review is being performed and scope should be agreed before testing.",
    reviewerGuidance: "Confirm project contacts, testing window, scope boundaries, environment readiness, and approval to test.",
    remediation: "Document review approval, testing scope, constraints, and stakeholder contacts before assessment start.",
  },
  {
    id: "6.3",
    title: "Authentication controls enforced server-side",
    category: "Authentication",
    owasp: "A07 Identification and Authentication Failures",
    cwe: "CWE-287",
    defaultSeverity: "High",
    detail: "Authentication decisions must be enforced on the server and should not be bypassable by manipulating client-side state.",
    reviewerGuidance: "Check unauthenticated access, direct URL access, role switch attempts, remember-me behavior, and auth mechanism notes.",
    remediation: "Enforce authentication and authorization server-side for every protected route, API, and sensitive workflow.",
  },
  {
    id: "7.1",
    title: "Authorization controls protect non-public data and functions",
    category: "Authorization",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-862",
    defaultSeverity: "High",
    detail: "Applications processing non-public data must enforce authorization controls across data, functions, and services.",
    reviewerGuidance: "Test horizontal and vertical access using each RBAC role, direct object access, hidden UI functions, and API calls.",
    remediation: "Implement deny-by-default authorization checks using server-side role, ownership, tenant, and object-level policy enforcement.",
  },
  {
    id: "9.3",
    title: "Application must not be susceptible to Cross-Site Scripting",
    category: "Input Validation",
    owasp: "A03 Injection",
    cwe: "CWE-79",
    defaultSeverity: "High",
    detail: "User-controlled input must be validated, encoded, and rendered safely to prevent reflected, stored, or DOM XSS.",
    reviewerGuidance: "Check inputs, rich text fields, comments, search, uploaded filenames, error messages, and client-side sinks.",
    remediation: "Validate input server-side, encode output by context, sanitize rich HTML, and use a restrictive CSP.",
  },
  {
    id: "9.4",
    title: "Application must not be susceptible to command injection",
    category: "Input Validation",
    owasp: "A03 Injection",
    cwe: "CWE-77",
    defaultSeverity: "Critical",
    detail: "Inputs must not allow execution of operating system commands, SQL, LDAP, XML, XPath, or similar command contexts.",
    reviewerGuidance: "Review command-like parameters, import/export processors, admin tools, search filters, integrations, and backend logs.",
    remediation: "Use parameterized APIs, strict allow-lists, no shell interpolation, least-privilege execution, and safe parser configuration.",
  },
  {
    id: "9.10",
    title: "Application must not be susceptible to Server-Side Request Forgery",
    category: "Input Validation",
    owasp: "A10 Server-Side Request Forgery",
    cwe: "CWE-918",
    defaultSeverity: "High",
    detail: "URL, webhook, image fetch, PDF, redirect, and integration inputs must not allow server-side access to internal resources.",
    reviewerGuidance: "Passively identify URL-fetching features and verify documented allow-listing, redirect blocking, and metadata IP protections.",
    remediation: "Restrict outbound fetches with allow-lists, block private/metadata ranges, disable redirects, and isolate fetch workers.",
  },
  {
    id: "11.1",
    title: "Secure tokens and credentials during network transmission",
    category: "Secure Communications",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-319",
    defaultSeverity: "High",
    detail: "Passwords, passphrases, PINs, session tokens, and static access tokens must be protected during transmission.",
    reviewerGuidance: "Confirm HTTPS-only transport, Secure cookies, no mixed content, no token in URL, and no sensitive data in query strings.",
    remediation: "Enforce HTTPS, HSTS, secure cookie attributes, POST body for sensitive values, and token redaction in logs.",
  },
  {
    id: "14.2",
    title: "Server-side code must not be exposed to end users",
    category: "Information Leakage",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-540",
    defaultSeverity: "High",
    detail: "Server-side source code, stack traces, templates, secrets, and implementation internals must not be delivered to clients.",
    reviewerGuidance: "Review errors, source maps, exposed bundles, debug endpoints, repository artifacts, and unexpected downloadable files.",
    remediation: "Disable debug output, remove source maps in production, restrict static directories, and sanitize errors.",
  },
  {
    id: "14.7",
    title: "Network services should not disclose software versions or configuration",
    category: "Information Leakage",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-200",
    defaultSeverity: "Medium",
    detail: "Network services should not reveal versions, installed packages, configuration details, or usernames unnecessarily.",
    reviewerGuidance: "Check headers, error pages, banners, comments, dependency files, and JavaScript bundles for version disclosure.",
    remediation: "Suppress version banners, remove sensitive comments, standardize error pages, and avoid leaking internal package details.",
  },
  {
    id: "15.18",
    title: "Forms-based email submissions must restrict sender address modification",
    category: "System Design & Architecture",
    owasp: "A04 Insecure Design",
    cwe: "CWE-640",
    defaultSeverity: "Medium",
    detail: "Forms-based email features should use a static sender identity and prevent unauthorized sender manipulation.",
    reviewerGuidance: "Check contact forms, invite flows, notification features, reply-to handling, and email header injection controls.",
    remediation: "Use server-controlled sender identities, validate reply-to fields, and protect mail headers from injection.",
  },
  {
    id: "16.14",
    title: "Internet-facing systems must implement security headers",
    category: "System Configuration",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-693",
    defaultSeverity: "Medium",
    detail: "Applications should set secure headers such as CSP, Cache-Control, X-Content-Type-Options, and frame protection.",
    reviewerGuidance: "Check CSP, HSTS, X-Frame-Options/frame-ancestors, Cache-Control, Referrer-Policy, and MIME sniffing protection.",
    remediation: "Configure a strict baseline of HTTP security headers and validate them across every deployed route.",
  },
  {
    id: "19.1",
    title: "JWT secret must resist brute forcing",
    category: "Web API Validation and Authentication",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-326",
    defaultSeverity: "High",
    detail: "JWT signing secrets must be random, sufficiently long, protected, and rotated through a secure secret-management process.",
    reviewerGuidance: "Confirm token algorithm, key management, issuer/audience validation, expiry, rotation, and no secrets in code.",
    remediation: "Use strong asymmetric keys or high-entropy managed secrets, validate token claims, and rotate keys periodically.",
  },
  {
    id: "19.2",
    title: "JWT algorithm must be enforced by the backend",
    category: "Web API Validation and Authentication",
    owasp: "A07 Identification and Authentication Failures",
    cwe: "CWE-347",
    defaultSeverity: "High",
    detail: "Token algorithms must not be trusted from user-controlled payloads; the backend must enforce the expected algorithm.",
    reviewerGuidance: "Check whether HS256/RS256 or stronger algorithms are configured, and confirm algorithm confusion is prevented.",
    remediation: "Pin allowed algorithms in server configuration and reject none/weak/unexpected algorithms.",
  },
  {
    id: "19.3",
    title: "Sensitive data must not be stored in JWT payload",
    category: "Web API Validation and Authentication",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-315",
    defaultSeverity: "Medium",
    detail: "JWT payloads are base64url encoded and must not contain sensitive personal, confidential, or authorization-critical data.",
    reviewerGuidance: "Decode sample tokens, review claims, check role/tenant exposure, and confirm no secrets or PII are present.",
    remediation: "Keep tokens minimal, store sensitive data server-side, and use opaque references where possible.",
  },
  {
    id: "19.6",
    title: "APIs must enforce usage quotas and rate limits",
    category: "Web API Validation and Authentication",
    owasp: "A04 Insecure Design",
    cwe: "CWE-770",
    defaultSeverity: "Medium",
    detail: "APIs should enforce per-user, per-client, and global rate limits to reduce abuse, brute force, and resource exhaustion.",
    reviewerGuidance: "Check auth endpoints, search APIs, export APIs, LLM calls, and expensive report-generation operations.",
    remediation: "Apply rate limiting, quotas, backoff, alerting, and abuse detection for sensitive and expensive API routes.",
  },
  {
    id: "21.1",
    title: "LLM application must not be susceptible to model denial of service",
    category: "LLM Application Security",
    owasp: "LLM04 Model Denial of Service",
    cwe: "CWE-400",
    defaultSeverity: "High",
    detail: "LLM-enabled workflows must protect model, token, tool, and retrieval resources from abusive or unbounded requests.",
    reviewerGuidance: "Check token limits, file limits, recursion/tool-call limits, long context ingestion, and rate limits.",
    remediation: "Enforce token budgets, file-size limits, request quotas, timeouts, tool-call caps, and cost monitoring.",
  },
  {
    id: "21.2",
    title: "LLM application must prevent sensitive data exfiltration",
    category: "LLM Application Security",
    owasp: "LLM02 Sensitive Information Disclosure",
    cwe: "CWE-200",
    defaultSeverity: "High",
    detail: "LLM workflows must not expose secrets, private context, uploaded files, hidden prompts, or unauthorized tenant data.",
    reviewerGuidance: "Check retrieval isolation, prompt-injection handling, output filtering, tenant boundaries, and tool response exposure.",
    remediation: "Apply retrieval access control, redaction, tenant isolation, least-privilege tools, and output safety checks.",
  },
  {
    id: "21.4",
    title: "LLM application must resist prompt injection and jailbreak attempts",
    category: "LLM Application Security",
    owasp: "LLM01 Prompt Injection",
    cwe: "CWE-1427",
    defaultSeverity: "High",
    detail: "LLM systems should treat user and retrieved content as untrusted and must not let it override system or policy instructions.",
    reviewerGuidance: "Review system prompt boundaries, retrieval instructions, tool use, indirect prompt injection, and refusal behavior.",
    remediation: "Separate instructions from data, constrain tools, validate outputs, use policy guards, and log attempted instruction override.",
  },
  {
    id: "21.5",
    title: "LLM application must prevent arbitrary plugin or tool invocation",
    category: "LLM Application Security",
    owasp: "LLM07 Insecure Plugin Design",
    cwe: "CWE-749",
    defaultSeverity: "High",
    detail: "Agents must not call arbitrary tools, plugins, APIs, or database mutations without allow-lists and approval gates.",
    reviewerGuidance: "Check tool allow-lists, role gates, dry-run/apply modes, audit logs, and command parameter validation.",
    remediation: "Use whitelisted tools, schema validation, role-based authorization, human approval, and immutable audit trails.",
  },
];
